[build]
builder = "nixpacks"
buildCommand = "npm install --prefix client && npm install --prefix server && npm run build --prefix client"

[deploy]
startCommand = "npm start"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
